# Generated by Django 4.1.7 on 2023-04-03 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.CharField(default='https://firebasestorage.googleapis.com/v0/b/techiebio-f4784.appspot.com/o/blank-profile-picture-female.png?alt=media&token=e4c7b614-223d-483e-a251-e8b20aa7fc53', max_length=1000),
        ),
    ]
